In [3]:
import pandas as pd
import numpy as np
import time

In [4]:
print('Numpy version: ' + np.__version__)

Numpy version: 1.23.4


## Create an Array
    list
    tuple
    range
    1D
    2D
    3D
    np.arange()
    np.linspace(): Create array of fixed length
    np.random.rand(): method returns values in the range [0,1)
    np.ones(): Create array of 1s , np.ones_like()
    np.zeros(): Create array of 0s , np.zeros_like()
    np.empty(), np.empty_like()
    np.full(),np.full_like()
    np.random.random(): Create array of random numbers
    
    np.arange(): Create array with increments of a fixed step size
        start: start number (inclusive)
        stop: end number (inclusive unless endpoint set to False)
        num_of_elements: number of elements contained in the array
        endpoint: boolean value representing whether the stop number is inclusive or not
        retstep: boolean value representing whether to return the step size
    
    np.random.rand()
    
    np.repeat(iterable, reps, axis=None): repeat each element by n times
        iterable: input array
        reps: number of repetitions
        axis: which axis to repeat along, default is None which will flatten the input array and then repeat
    
    np.tile(): repeat the whole array by n times
        iterable: input array
        reps: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis
    
    np.eye(size, k=0): create an identity matrix of given size
        size: the size of the identity matrix
        k: the diagonal offset
    
    np.identity(): same as np.eye() but does not carry parameters
    
    Create an array with given values on the diagonal
    time calculation between list and array

In [5]:
# 1D list
np.array([2,56,4,8,9,9])

array([ 2, 56,  4,  8,  9,  9])

In [6]:
#1D tuple
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [7]:
# range
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#2D
np.array([[1,2,3,4],[5,6,6,7]])

array([[1, 2, 3, 4],
       [5, 6, 6, 7]])

In [9]:
#3D
np.array([[[1,2,3],[2,3,4]],[[3,4,5],[5,6,7]]])

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [5, 6, 7]]])

In [10]:
# arange
np.arange(10,50,6)

array([10, 16, 22, 28, 34, 40, 46])

In [11]:
#linspace
np.linspace(10,50,10)

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

In [12]:
#linspace

np.linspace(10,50,10,endpoint=False,retstep=True)

(array([10., 14., 18., 22., 26., 30., 34., 38., 42., 46.]), 4.0)

In [13]:
#random.rand() in between 0 to 1
np.random.rand()

0.43168689356832146

In [14]:
np.random.rand(3)

array([0.77995848, 0.92409315, 0.91933683])

In [15]:
np.random.rand(4,4)

array([[0.28148355, 0.31516543, 0.67213124, 0.77313266],
       [0.21595836, 0.94798189, 0.36103203, 0.66318187],
       [0.72378932, 0.27216743, 0.89328594, 0.9681246 ],
       [0.52912107, 0.15863033, 0.28809028, 0.79546563]])

In [16]:
np.random.randint(10,50,(4,4))

array([[38, 29, 49, 20],
       [40, 16, 43, 34],
       [49, 10, 14, 15],
       [21, 18, 27, 22]])

In [17]:
# zeros
np.zeros(1,dtype="int32")

array([0], dtype=int32)

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
a=np.random.randint(1,10,(3,2))
a

array([[3, 5],
       [9, 7],
       [3, 2]])

In [21]:
np.zeros_like(a)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [22]:
# ones
np.ones(2)

array([1., 1.])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
c=np.ones((5,3),dtype="int64")
print(c)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [25]:
b=np.ones_like(a)
print(b)
print("ones like:"+str(b.dtype))

[[1 1]
 [1 1]
 [1 1]]
ones like:int64


In [26]:
# empty
np.empty(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.empty((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.empty_like(a)

array([[94577623948082,              0],
       [             0,              0],
       [             0,              0]])

In [29]:
# full
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [30]:
np.full_like(a,3)

array([[3, 3],
       [3, 3],
       [3, 3]])

In [31]:
#repeat
np.repeat(a,3,axis=0)

array([[3, 5],
       [3, 5],
       [3, 5],
       [9, 7],
       [9, 7],
       [9, 7],
       [3, 2],
       [3, 2],
       [3, 2]])

In [32]:
np.repeat(a,4,axis=1)

array([[3, 3, 3, 3, 5, 5, 5, 5],
       [9, 9, 9, 9, 7, 7, 7, 7],
       [3, 3, 3, 3, 2, 2, 2, 2]])

In [33]:
#tile
np.tile(a,2)

array([[3, 5, 3, 5],
       [9, 7, 9, 7],
       [3, 2, 3, 2]])

In [34]:
np.tile(a,(3,3))

array([[3, 5, 3, 5, 3, 5],
       [9, 7, 9, 7, 9, 7],
       [3, 2, 3, 2, 3, 2],
       [3, 5, 3, 5, 3, 5],
       [9, 7, 9, 7, 9, 7],
       [3, 2, 3, 2, 3, 2],
       [3, 5, 3, 5, 3, 5],
       [9, 7, 9, 7, 9, 7],
       [3, 2, 3, 2, 3, 2]])

In [35]:
#eye
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(6,k=-2)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [37]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
#diag
c=np.random.randint(10,30,(3,3))
c

array([[13, 29, 17],
       [25, 26, 20],
       [25, 11, 15]])

In [39]:
np.diag(c)

array([13, 26, 15])

In [40]:
np.trace(c)

54

In [41]:
list_1 = [3, 6, 7, 5]
list_2 = [4, 5, 1, 7]

In [42]:
#list product
list_product=list(map(lambda x,y:x*y,list_1,list_2))
list_product

[12, 30, 7, 35]

In [43]:
arr_1=np.array(list_1)
arr_2=np.array(list_2)

In [44]:
# array product
arr_product=arr_1*arr_2
arr_product

array([12, 30,  7, 35])

In [45]:
list_square=[i**2 for i in list_1]
list_square

[9, 36, 49, 25]

In [46]:
arr_square=arr_1**2
arr_square

array([ 9, 36, 49, 25])

In [47]:
list_11=[i for i in range(10000000) ]
list_22=[j**2 for j in range(10000000)]

In [48]:
t0=time.time()
list_p=list(map(lambda x,y:x*y,list_11,list_22))
t1=time.time()
tt=t1-t0
print(tt)

1.4701833724975586


In [49]:
ar1=np.array(list_11)
ar2=np.array(list_22)
t0=time.time()
array_p=ar1*ar2
t1=time.time()
ttt=t1-t0
print(ttt)

0.02044057846069336


In [50]:
print("ratio of time taken:",tt/ttt)

ratio of time taken: 71.92474397555229


## Data Types in NumPy
Numpy has the following data types:

    int
    float
    complex
    bool
    string
    unicode
    object

In [51]:
dtypes = pd.DataFrame(
    {
        'Type': [
            'int8', 
            'uint8', 
            'int16', 
            'uint16', 
            'int or int32', 
            'uint32', 
            'int64', 
            'uint64', 
            'float16', 
            'float32', 
            'float or float64',
            'float128', 
            'complex64', 
            'complex or complex128', 
            'bool', 
            'object', 
            'string_',
            'unicode_',
        ],
        
        'Type Code': [
            'i1', 
            'u1', 
            'i2', 
            'u2', 
            'i4 or i', 
            'u4', 
            'i8', 
            'u8', 
            'f2', 
            'f4 or f', 
            'f8 or d', 
            'f16 or g', 
            'c8', 
            'c16', 
            None, 
            'O', 
            'S', 
            'U',
        ]
    }
)

dtypes

Type Type Code
0                    int8        i1
1                   uint8        u1
2                   int16        i2
3                  uint16        u2
4            int or int32   i4 or i
5                  uint32        u4
6                   int64        i8
7                  uint64        u8
8                 float16        f2
9                 float32   f4 or f
10       float or float64   f8 or d
11               float128  f16 or g
12              complex64        c8
13  complex or complex128       c16
14                   bool      None
15                 object         O
16                string_         S
17               unicode_         U

## Inspect an Array
    shape
    size
    info
    dtype
    len
    ndim
    itemsize
    nbytes

In [52]:
e=np.random.randint(10,100,(5,5))
e

array([[95, 85, 96, 16, 32],
       [62, 50, 12, 44, 12],
       [67, 67, 71, 65, 41],
       [29, 81, 88, 91, 35],
       [40, 63, 27, 48, 13]])

In [53]:
e.shape

(5, 5)

In [54]:
e.size

25

In [55]:
len(e)

5

In [56]:
np.info(e)

class:  ndarray
shape:  (5, 5)
strides:  (40, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x5601f0c1fba0
byteorder:  little
byteswap:  False
type: int64


In [57]:
e.ndim

2

In [58]:
e.dtype

dtype('int64')

In [59]:
e.itemsize

8

In [60]:
e.nbytes

200

## NumPy Random Array
    np.random.rand()
    np.random.randn()
    np.random.randint()
    np.random.ranf()
    np.random.random_sample()
    np.random.sample()
    np.random.choice(iterable_or_int, size, replace=True, p=weights)
    np.random.shuffle()
    np.random.permutation()

In [61]:
np.random.rand(5)

array([0.62878077, 0.80435478, 0.4985463 , 0.28270716, 0.57019386])

In [62]:
np.random.rand(3,3)

array([[0.91836156, 0.64618269, 0.46783679],
       [0.04007061, 0.10164747, 0.55806213],
       [0.15065532, 0.26522377, 0.11696524]])

In [63]:
np.random.rand()

0.443636086957671

In [64]:
np.random.randn(3,3)

array([[ 0.03737826,  0.19778698, -1.30885795],
       [ 0.33403107, -2.40786153,  0.24405654],
       [-0.12896344,  0.0983282 , -0.55910248]])

In [65]:
np.random.randint(10,20,15)

array([10, 18, 19, 11, 15, 18, 12, 15, 17, 10, 12, 17, 16, 14, 19])

In [66]:
np.random.randint(10,20,(3,3))

array([[10, 18, 12],
       [19, 19, 13],
       [14, 12, 19]])

In [67]:
np.random.ranf(10)

array([0.50137964, 0.58339705, 0.26056787, 0.06654666, 0.02118088,
       0.40459109, 0.02971537, 0.06675823, 0.20902512, 0.7005901 ])

In [68]:
np.random.sample(10)

array([0.3611449 , 0.25055405, 0.98591931, 0.19519881, 0.227657  ,
       0.23870304, 0.50949496, 0.40253529, 0.28628334, 0.95075118])

In [69]:
np.random.random_sample(10)

array([0.06965823, 0.61712227, 0.79501187, 0.21625376, 0.98808214,
       0.60472146, 0.43275553, 0.3905142 , 0.22327145, 0.99087074])

In [70]:
g=np.random.choice(5,15)
g

array([2, 1, 2, 1, 1, 4, 1, 1, 4, 2, 1, 4, 4, 0, 2])

In [71]:
np.random.choice(5,(4,4))

array([[4, 3, 0, 2],
       [2, 3, 3, 1],
       [4, 2, 2, 2],
       [1, 3, 2, 3]])

In [72]:
np.random.choice([5,6,4],(3,3))

array([[4, 6, 4],
       [6, 6, 6],
       [6, 4, 4]])

In [73]:
f=np.random.choice(range(10),(6,6))
f

array([[4, 3, 4, 7, 4, 8],
       [8, 2, 1, 6, 5, 7],
       [5, 6, 5, 9, 2, 1],
       [7, 8, 1, 5, 6, 3],
       [8, 3, 1, 0, 9, 2],
       [4, 3, 2, 0, 9, 4]])

In [74]:
f=np.random.shuffle(f)
f

In [75]:
np.random.permutation(g)

array([4, 1, 1, 0, 1, 1, 4, 2, 1, 2, 1, 2, 4, 4, 2])

## NumPy Math Functions
    Element-wise addition, subtraction, multiplication and division
    +,-,*,/
    add,subtract,multiply
    exp,log,log2,log10,sqrt,sin,cos
    
    axis based operations
        sum,min,max,argmin,argmax,mean,median,std,var,corr,corrcoef,cov,cumsum,cumprod
    percentile
    re, intg = np.modf(arr1)
    Compute element-wise min and max of two arrays
        minimum,maximum
    Split fractional and integral parts of a floating-point arrays
    
    Element-wise comparison

In [76]:
x=np.random.randint(10,50,6)
y=np.random.randint(10,20,6)

In [77]:
print("x:",x)
print("y:",y)

x: [30 28 16 33 39 22]
y: [18 12 14 18 13 15]


In [78]:
x+10

array([40, 38, 26, 43, 49, 32])

In [79]:
x-10

array([20, 18,  6, 23, 29, 12])

In [80]:
x*10

array([300, 280, 160, 330, 390, 220])

In [81]:
x/10

array([3. , 2.8, 1.6, 3.3, 3.9, 2.2])

In [82]:
np.add(x,5,out=x)

array([35, 33, 21, 38, 44, 27])

In [83]:
np.subtract(x,6,out=x)

array([29, 27, 15, 32, 38, 21])

In [84]:
np.multiply(x,2,out=x)

array([58, 54, 30, 64, 76, 42])

## Subset, Slice, Index and Iterate through Arrays
    Slicing arrays
        Slicing in python means taking elements from one given index to another given index.

    We pass slice instead of index like this: [start:end].
    We can also define the step, like this: [start:end:step].
    If we don't pass start its considered 0
    If we don't pass end its considered length of array in that dimension
    If we don't pass step its considered 1

In [85]:
# Indexing and Slicing One Dimensional Arrays
arr=np.random.randint(10,20,10)
arr

array([17, 16, 14, 10, 16, 15, 18, 18, 13, 13])

In [86]:
arr[0]

17

In [87]:
arr[[5,8,2]]

array([15, 13, 14])

In [88]:
arr[6:]

array([18, 18, 13, 13])

In [89]:
arr[:4]

array([17, 16, 14, 10])

In [90]:
arr[5:8]

array([15, 18, 18])

In [91]:
arr[-1:]

array([13])

In [92]:
arr[2:10:3]

array([14, 15, 13])

In [93]:
for i in arr:
    print(i**2)

289
256
196
100
256
225
324
324
169
169


In [94]:
# Indexing and Slicing on 2-D Arrays
z=np.random.choice(50,(5,4))
z

array([[ 0, 20,  4,  1],
       [45,  8, 11,  1],
       [48, 17, 14,  6],
       [37, 21, 11, 42],
       [11, 30, 27, 12]])

In [95]:
z[0]

array([ 0, 20,  4,  1])

In [96]:
z[1][2]

11

In [97]:
z[2,1]

17

In [98]:
z[:,2:]

array([[ 4,  1],
       [11,  1],
       [14,  6],
       [11, 42],
       [27, 12]])

In [99]:
z[:,:1]

array([[ 0],
       [45],
       [48],
       [37],
       [11]])

In [100]:
z[1:,:]

array([[45,  8, 11,  1],
       [48, 17, 14,  6],
       [37, 21, 11, 42],
       [11, 30, 27, 12]])

In [101]:
z[:1,1:]

array([[20,  4,  1]])

In [102]:
z[:,:]

array([[ 0, 20,  4,  1],
       [45,  8, 11,  1],
       [48, 17, 14,  6],
       [37, 21, 11, 42],
       [11, 30, 27, 12]])

In [103]:
for i in z:
    print(i)

[ 0 20  4  1]
[45  8 11  1]
[48 17 14  6]
[37 21 11 42]
[11 30 27 12]


In [104]:
# 3D
w=np.arange(24).reshape(2,3,4)
w

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [105]:
for i in w:
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [106]:
w[1][1][2]

18

In [107]:
#Boolean Indexing
v=np.arange(36).reshape(6,6)
v

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [108]:
bools=np.array([True,True,False,True,False,True])

In [109]:
v[bools]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23],
       [30, 31, 32, 33, 34, 35]])

In [110]:
v[~bools]

array([[12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [111]:
# Find elements/indices by conditions
u=np.arange(25).reshape(5,5)
u

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [112]:
u[u>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [113]:
np.where(u>10,-1,10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [114]:
np.argwhere((arr>5))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [115]:
# Sorting of an Array
f=np.random.choice(50,(5,5))
f

array([[ 4, 45, 42, 36,  4],
       [41, 42, 36, 10, 25],
       [12, 19,  4, 29, 40],
       [30, 36,  9, 40, 43],
       [18,  8, 32, 45,  2]])

In [116]:
np.sort(f)

array([[ 4,  4, 36, 42, 45],
       [10, 25, 36, 41, 42],
       [ 4, 12, 19, 29, 40],
       [ 9, 30, 36, 40, 43],
       [ 2,  8, 18, 32, 45]])

In [117]:
np.sort(f,axis=0)

array([[ 4,  8,  4, 10,  2],
       [12, 19,  9, 29,  4],
       [18, 36, 32, 36, 25],
       [30, 42, 36, 40, 40],
       [41, 45, 42, 45, 43]])

In [118]:
np.sort(f,axis=1)

array([[ 4,  4, 36, 42, 45],
       [10, 25, 36, 41, 42],
       [ 4, 12, 19, 29, 40],
       [ 9, 30, 36, 40, 43],
       [ 2,  8, 18, 32, 45]])

In [119]:
f.sort(axis=0)
f

array([[ 4,  8,  4, 10,  2],
       [12, 19,  9, 29,  4],
       [18, 36, 32, 36, 25],
       [30, 42, 36, 40, 40],
       [41, 45, 42, 45, 43]])

In [120]:
f.sort(axis=1)
f

array([[ 2,  4,  4,  8, 10],
       [ 4,  9, 12, 19, 29],
       [18, 25, 32, 36, 36],
       [30, 36, 40, 40, 42],
       [41, 42, 43, 45, 45]])

In [121]:
# Order parameter in sort function
dt = np.dtype([('name', 'S10'),('age', int)]) 
arr = np.array([("Karan",21),("Arpit",25),("Ashish", 17), ("Sam",27),("Robin",22)], dtype = dt)  
arr 

array([(b'Karan', 21), (b'Arpit', 25), (b'Ashish', 17), (b'Sam', 27),
       (b'Robin', 22)], dtype=[('name', 'S10'), ('age', '<i8')])

In [122]:
np.sort(arr,order="name")

array([(b'Arpit', 25), (b'Ashish', 17), (b'Karan', 21), (b'Robin', 22),
       (b'Sam', 27)], dtype=[('name', 'S10'), ('age', '<i8')])

In [123]:
np.sort(arr,order="age")

array([(b'Ashish', 17), (b'Karan', 21), (b'Robin', 22), (b'Arpit', 25),
       (b'Sam', 27)], dtype=[('name', 'S10'), ('age', '<i8')])

In [124]:
# compute the indices that would sort an array along a specified axis
ass=np.random.randint(10,60,(4,5))
ass

array([[44, 25, 49, 49, 27],
       [44, 39, 33, 33, 56],
       [33, 14, 57, 53, 10],
       [31, 20, 23, 45, 11]])

In [125]:
np.argsort(ass)

array([[1, 4, 0, 2, 3],
       [2, 3, 1, 0, 4],
       [4, 1, 0, 3, 2],
       [4, 1, 2, 0, 3]])

In [126]:
np.argsort(ass,axis=0)

array([[3, 2, 3, 1, 2],
       [2, 3, 1, 3, 3],
       [0, 0, 0, 0, 0],
       [1, 1, 2, 2, 1]])

In [127]:
np.argsort(ass,axis=1)

array([[1, 4, 0, 2, 3],
       [2, 3, 1, 0, 4],
       [4, 1, 0, 3, 2],
       [4, 1, 2, 0, 3]])

In [128]:
np.argsort(ass,axis=None)

array([14, 19, 11, 16, 17,  1,  4, 15,  7,  8, 10,  6,  0,  5, 18,  3,  2,
       13,  9, 12])

## Numpy Array Manipulation
    Transpose an array
    numpy.swapaxes() function interchange two axes of an array
        Syntax : numpy.swapaxes(arr, axis1, axis2)
    3D Array
    Change the shape of an array
    flatten an array
    append elements to an array
    insert elements into an array
    delete elements from an array
    copy an array

In [129]:
g=np.arange(16).reshape(4,4)
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [130]:
g.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [131]:
np.transpose(g)

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [132]:
g.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [133]:
np.swapaxes(g, 1,0)

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [134]:
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [135]:
arr1 = np.arange(16).reshape((2,2,4))
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [136]:
np.swapaxes(arr1, 0, 1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [137]:
# Change the shape of an array
xx=np.arange(12)
xx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [138]:
xx.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [139]:
xx.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [140]:
# flatten an array
# return a copy
g.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [141]:
# return a view
# change any element in the view will change the initial array
arr.ravel()   

array([(b'Karan', 21), (b'Arpit', 25), (b'Ashish', 17), (b'Sam', 27),
       (b'Robin', 22)], dtype=[('name', 'S10'), ('age', '<i8')])

In [142]:
# append elements to an array
np.append(g,22)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 22])

In [143]:
np.append(g,[5,6,2,3,2])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,  5,
        6,  2,  3,  2])

## Combine & Split an Array
    concatenate
    vstack
    hstack
    vsplit
    hsplit

In [145]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [146]:
np.concatenate((arr1, arr2), axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [147]:
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [148]:
np.vstack((arr1, arr2))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [149]:
np.hstack((arr1, arr2))

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [151]:
np.vsplit(arr1, 2)

[array([[1, 2, 3, 4]]), array([[1, 2, 3, 4]])]

In [152]:
np.hsplit(arr2, 2)

[array([[5, 6],
        [5, 6]]),
 array([[7, 8],
        [7, 8]])]

# Numpy Set Operations
    unique
    counts
    intersection1d
    union1d
    in1d
    isin
    setdiff1d
    setxor1d    

In [153]:
arr = np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


In [155]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


In [156]:
np.intersect1d(arr1, arr2)

array([], dtype=int64)

In [157]:
np.union1d(arr1, arr2)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [158]:
np.in1d(arr1, arr2)

array([False, False, False, False, False, False, False, False])

In [159]:
np.isin(arr1, arr2)

array([[False, False, False, False],
       [False, False, False, False]])

In [160]:
np.setdiff1d(arr1, arr2)

array([1, 2, 3, 4])

In [161]:
np.setxor1d(arr1, arr2)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Linear Algebra
    dot
    qr
    svd
    eigvals
    eig
    

In [167]:
array_1=np.random.choice(10,(5,5))
array_2=np.random.choice(20,(5,5))

In [168]:
array_1

array([[5, 2, 9, 5, 8],
       [9, 2, 3, 5, 8],
       [7, 8, 8, 0, 8],
       [3, 4, 9, 9, 4],
       [6, 8, 1, 7, 0]])

In [169]:
array_2

array([[ 6, 11,  8, 18, 18],
       [ 6,  4,  4, 18, 17],
       [ 9,  6,  7, 13, 10],
       [ 0, 13, 13, 12,  0],
       [ 9,  2, 12, 15,  0]])

In [170]:
# matrix product
array_1.dot(array_2)

array([[195, 198, 272, 423, 214],
       [165, 206, 262, 417, 226],
       [234, 173, 240, 494, 342],
       [159, 228, 268, 411, 212],
       [ 93, 195, 178, 349, 254]])

In [171]:
np.dot(array_1,array_2)

array([[195, 198, 272, 423, 214],
       [165, 206, 262, 417, 226],
       [234, 173, 240, 494, 342],
       [159, 228, 268, 411, 212],
       [ 93, 195, 178, 349, 254]])

In [174]:
# QR factorization
arr = np.random.rand(5,5)
q,r=np.linalg.qr(arr)
print(q)
print(r)

[[-0.67879111  0.38978768  0.2978779  -0.54530253 -0.0349587 ]
 [-0.19143197 -0.31434046  0.59622462  0.3780854  -0.60507149]
 [-0.70491702 -0.19992246 -0.45341547  0.47552642  0.17723444]
 [-0.07054364 -0.79763735 -0.16803707 -0.56873684 -0.08426267]
 [-0.02668388 -0.27029854  0.56741777  0.10054656  0.77081394]]
[[-1.0850121  -0.70512694 -0.57820077 -1.20468263 -0.60821038]
 [ 0.         -1.11869272 -0.32280224 -0.7897626  -0.63940622]
 [ 0.          0.          0.77620756  0.07291113  0.0066737 ]
 [ 0.          0.          0.         -0.44746283  0.21675671]
 [ 0.          0.          0.          0.          0.37913738]]


In [175]:
# singular value decomposition (SVD)
arr = np.random.rand(5,5)
u,s,v=np.linalg.svd(arr)

In [176]:
u

array([[-0.36539548,  0.02499591,  0.87050916, -0.31559495, -0.09205958],
       [-0.31444237, -0.75921457, -0.10146416, -0.13471713,  0.54431199],
       [-0.50739866,  0.59646771, -0.32094594, -0.36401146,  0.38892446],
       [-0.5297898 , -0.23561329, -0.33920617, -0.12807611, -0.72961964],
       [-0.47904228,  0.10807907,  0.11769322,  0.85635465,  0.10790007]])

In [177]:
s

array([2.59739892, 0.74062998, 0.59284237, 0.43288619, 0.27682835])

In [178]:
v

array([[-0.3719445 , -0.28744768, -0.50275948, -0.54474353, -0.47908091],
       [ 0.64715421, -0.07346356,  0.38968529, -0.63458729, -0.14573566],
       [ 0.02745512, -0.56951785,  0.36709427,  0.45237385, -0.57921959],
       [-0.06028103, -0.75463169, -0.00228574, -0.12288897,  0.64170888],
       [ 0.66216398, -0.13474928, -0.67868612,  0.2842704 , -0.04423775]])

In [179]:
# compute eigen values
np.linalg.eigvals(arr)

array([ 2.59619053+0.j        ,  0.43196331+0.34604932j,
        0.43196331-0.34604932j, -0.28201144+0.30382194j,
       -0.28201144-0.30382194j])

In [181]:
# eigen value decomposition
w,v=np.linalg.eig(arr)

In [182]:
w

array([ 2.59619053+0.j        ,  0.43196331+0.34604932j,
        0.43196331-0.34604932j, -0.28201144+0.30382194j,
       -0.28201144-0.30382194j])

In [183]:
v

array([[-0.36343048+0.j        ,  0.15036895+0.32881889j,
         0.15036895-0.32881889j,  0.58697429-0.06689274j,
         0.58697429+0.06689274j],
       [-0.3135037 +0.j        , -0.61542039+0.j        ,
        -0.61542039-0.j        ,  0.02969339-0.3443252j ,
         0.02969339+0.3443252j ],
       [-0.50965908+0.j        ,  0.21774222+0.20960804j,
         0.21774222-0.20960804j, -0.61534896+0.j        ,
        -0.61534896-0.j        ],
       [-0.53255094+0.j        , -0.30431176-0.06058852j,
        -0.30431176+0.06058852j,  0.07215868+0.34732034j,
         0.07215868-0.34732034j],
       [-0.47567935+0.j        ,  0.36586005-0.41115407j,
         0.36586005+0.41115407j,  0.09451948-0.13460474j,
         0.09451948+0.13460474j]])

In [184]:
np.trace(arr)

2.896094276096256

In [185]:
np.linalg.det(arr)

0.1366669424187831

In [186]:
np.linalg.inv(arr)

array([[-0.06177609,  0.69767125,  1.55996641, -1.87311019,  0.30732977],
       [-0.2033282 ,  0.17747433,  0.75055937,  0.98628176, -1.61613618],
       [ 0.85027135, -1.73517796, -0.73827036,  1.55798663, -0.04658711],
       [ 0.71452373,  1.23622348, -0.14683519, -0.6587206 , -0.03463326],
       [-1.24115405,  0.01983663, -0.3119698 ,  0.4022269 ,  1.20431616]])

In [187]:
# solve a linear system
# solve a linear system in closed form
y = [1,2,3,4,5]
print(np.linalg.solve(arr, y))

[ 0.05767369 -1.73225529  1.16411529 -0.06158358  5.49309821]
