# 1.NUMPY 
* pip install numpy
* pip uninstall numpy
* import numpy
* numpy.__version__


In [5]:
import numpy as np
numpy.__version__

'1.21.5'

# 2.creating nd array

In [195]:
z=np.array(26)
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3,4,5],[4,5,6,7,8]])
c=np.array([[[2,17,14], [66,45, 78]], [[89,88, 92], [55,60, 76]],[[76,89,33],[12,20,18]]])

a

a[0]

a[3]

print(z)

b[0][1]

a

b

c

c[0][1][1]

a.ndim

b.ndim

c.ndim

c[1][1][2]

type(a)
type(b)
type(c)

26


numpy.ndarray

# 3.Array with existing data
    1.asarray(input,dtype,order)
            a.input----list,tuple
            b.dtype---- int ,str,bytes,float
            c.order----row major order 'C' column major order 'F'
    2.frombuffer(buffer,dtype,count,offset)
            a.buffer----list,tuple
            b.dtype---- int ,str,bytes,float
            c.count----length of array
            d.offset----position
    3.fromiter(iterable,dtype,count)
            a.iterable----list,tuple
            b.dtype---- int ,str,bytes,float
            c.count----length of array

In [196]:
c=np.array([[[2,17,14], [66,45, 78]], [[89,88, 92], [55,60, 76]],[[76,89,33],[12,20,18]]])

In [204]:
u=np.asarray(c,dtype="float",order="F")

v=np.asarray(c,dtype="int",order="F")

w=np.asarray(c,dtype="float",order="C")

x=np.asarray(c,dtype="int",order="C")

In [205]:
u

array([[[ 2., 17., 14.],
        [66., 45., 78.]],

       [[89., 88., 92.],
        [55., 60., 76.]],

       [[76., 89., 33.],
        [12., 20., 18.]]])

In [206]:
for i in np.nditer(u):
    print(i)

2.0
89.0
76.0
66.0
55.0
12.0
17.0
88.0
89.0
45.0
60.0
20.0
14.0
92.0
33.0
78.0
76.0
18.0


In [207]:
v

array([[[ 2, 17, 14],
        [66, 45, 78]],

       [[89, 88, 92],
        [55, 60, 76]],

       [[76, 89, 33],
        [12, 20, 18]]])

In [208]:
for i in np.nditer(v):
    print(i)

2
89
76
66
55
12
17
88
89
45
60
20
14
92
33
78
76
18


In [209]:
w

array([[[ 2., 17., 14.],
        [66., 45., 78.]],

       [[89., 88., 92.],
        [55., 60., 76.]],

       [[76., 89., 33.],
        [12., 20., 18.]]])

In [211]:
for i in np.nditer(w):
    print(i)

2.0
17.0
14.0
66.0
45.0
78.0
89.0
88.0
92.0
55.0
60.0
76.0
76.0
89.0
33.0
12.0
20.0
18.0


In [212]:
x

array([[[ 2, 17, 14],
        [66, 45, 78]],

       [[89, 88, 92],
        [55, 60, 76]],

       [[76, 89, 33],
        [12, 20, 18]]])

In [214]:
for i in np.nditer(x):
    print(i)

2
17
14
66
45
78
89
88
92
55
60
76
76
89
33
12
20
18


In [215]:
s=b"hai this is shekhar"

In [217]:
z=np.frombuffer(s,dtype="S1",count=10,offset=0)

In [218]:
z

array([b'h', b'a', b'i', b' ', b't', b'h', b'i', b's', b' ', b'i'],
      dtype='|S1')

In [220]:
y=np.fromiter(s,dtype="S1",count=11)

In [221]:
y

array([b'1', b'9', b'1', b'3', b'1', b'1', b'1', b'1', b'3', b'1', b'1'],
      dtype='|S1')

In [222]:
list=[5,6,4,8,9,4,7,8,9,3]

In [223]:
list

[5, 6, 4, 8, 9, 4, 7, 8, 9, 3]

In [226]:
np.fromiter(list,dtype="float",count=7)

array([5., 6., 4., 8., 9., 4., 7.])

# 4.Range
    1.np.arange(startindex,endindex,dtype)
    2.np.linespace(start index,start index, num,endpoint,retstep,dtype)
    3.np.logspace(start index,stop index,num,end point,base,dtype)

In [227]:
A=np.arange(0,10,1,dtype="float")
A

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [228]:
np.arange(0,10,1,dtype="int")


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [230]:
A=np.arange(9,10,1,dtype="int")
A

array([9])

In [249]:
np.linspace(1,10,4,endpoint=True,retstep=True,dtype="int")

(array([ 1,  4,  7, 10]), 3.0)

In [239]:
B=np.linspace(1,10,3,endpoint=False,retstep=True,dtype="int")

In [240]:
B

(array([1, 4, 7]), 3.0)

In [257]:
np.logspace(0,10,3,endpoint=True,base=2,dtype="int")

array([   1,   32, 1024])

In [258]:
np.logspace(0,10,endpoint=True,base=2,dtype="int")

array([   1,    1,    1,    1,    1,    2,    2,    2,    3,    3,    4,
          4,    5,    6,    7,    8,    9,   11,   12,   14,   16,   19,
         22,   25,   29,   34,   39,   45,   52,   60,   69,   80,   92,
        106,  122,  141,  162,  187,  216,  248,  286,  330,  380,  438,
        504,  581,  669,  771,  888, 1024])

# 5.Initializing arrays
    1.np.reshape(a,(x,y))
    2.np.zeros((2,3),dtype="xxxxxx")
    3.np.ones((shape),dtype)
    4.np.full((shape),value)
    5.np.eye((shape),dtye)
    6.

In [260]:
ll=[5,6,3,4]
np.reshape(ll,(2,2))

array([[5, 6],
       [3, 4]])

In [261]:
np.reshape(ll,(4,1))

array([[5],
       [6],
       [3],
       [4]])

In [262]:
np.reshape(ll,(1,4))

array([[5, 6, 3, 4]])

In [264]:
np.zeros((3,2),dtype="int")

array([[0, 0],
       [0, 0],
       [0, 0]])

In [265]:
np.zeros((3,3),dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [266]:
np.ones((3,2),dtype="int")

array([[1, 1],
       [1, 1],
       [1, 1]])

In [267]:
np.ones((4,4),dtype="float")

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [268]:
np.full((3,3),4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [269]:
np.full((3,4),3*2)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [274]:
np.eye(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# 6.7.Accessing and slicing elements from array
    1.a[]
    2.a[][]=a[x,y]
    3.a[][][]=a[x,y,z]
    4.a[-1]
# 1D
    5.[start index[0]:stop index:step index[1]]-------exclude stop index iiiiiiimmmmmmmmmmppppppppp
    6.[::]---gives all the elements
# 2D
    7.[index,:]
    8.[:,:]---[index1:inde2,sp index:ep in index
# 3D
    9.[0,1,1:4]
    10.slicing operation for each dimention will be performed

In [275]:
a

array([1, 2, 3, 4, 5])

In [276]:
b

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [277]:
c

array([[[ 2, 17, 14],
        [66, 45, 78]],

       [[89, 88, 92],
        [55, 60, 76]],

       [[76, 89, 33],
        [12, 20, 18]]])

In [278]:
a[0]

1

In [280]:
a[2]

3

In [281]:
a[:]

array([1, 2, 3, 4, 5])

In [283]:
a[-1]

5

In [285]:
a[1:2]

array([2])

In [286]:
a[1:5:2]

array([2, 4])

In [287]:
a[::-1]

array([5, 4, 3, 2, 1])

In [289]:
b

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [290]:
b[1,1]

5

In [291]:
b[1][1]

5

In [293]:
b[0:1,2:4]

array([[3, 4]])

In [294]:
c

array([[[ 2, 17, 14],
        [66, 45, 78]],

       [[89, 88, 92],
        [55, 60, 76]],

       [[76, 89, 33],
        [12, 20, 18]]])

In [295]:
c[0]

array([[ 2, 17, 14],
       [66, 45, 78]])

In [296]:
c[0,1]

array([66, 45, 78])

In [297]:
c[0,1,0:1]

array([66])

# 8.Axis
   1. for columns axis=0
   2. for row axis=1

In [306]:
a=np.arange(0,11,2)

In [307]:
a

array([ 0,  2,  4,  6,  8, 10])

In [312]:
b=np.reshape(a,(3,2))

In [314]:
np.sort(b,axis=0)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [315]:
np.sort(b,axis=1)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

# 9.data types copy(),view()
    i-----int
    s-----string
    f-----float
    u-----unicode strings
    m-----time delta
    M-----date time
    o-----object
    v-----void
        32 bit or 64 bit
    x=a.astype("f")
    view()---------create a reference to existing array
    copy()---------

In [350]:
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [351]:
c=a.copy()

In [352]:
c

array([1, 2, 3, 4, 5, 6, 7])

In [353]:
c[1]

2

In [354]:
c[0]

1

In [355]:
v=a.view()

In [356]:
v

array([1, 2, 3, 4, 5, 6, 7])

In [357]:
v[0]=10

In [358]:
v

array([10,  2,  3,  4,  5,  6,  7])

In [359]:
a[2]=500

In [360]:
a

array([ 10,   2, 500,   4,   5,   6,   7])

In [361]:
v


array([ 10,   2, 500,   4,   5,   6,   7])

In [362]:
c

array([1, 2, 3, 4, 5, 6, 7])

# 10.joining two arrays
        1.concatenate((a,b,c),axis=0/1)
        2.stack((a,b))
        3.vstack((a,b))
        4.hstack((a,b))
        5.dstack((a,b))

In [371]:
a=np.arange(0,50,2).reshape(5,5)

In [372]:
len(a)

5

In [373]:
a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [379]:
b=np.arange(0,100,2).reshape(10,5)

In [388]:
d=b[1:6,:]

In [385]:
len(b)

10

In [389]:
c=np.concatenate((a,d),axis=1)

In [390]:
c

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [30, 32, 34, 36, 38, 40, 42, 44, 46, 48],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]])

In [391]:
c=np.concatenate((a,d),axis=0)

In [392]:
c

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [393]:
a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [394]:
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [395]:
c

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [396]:
d

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [398]:
np.stack((a,d))

array([[[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38],
        [40, 42, 44, 46, 48]],

       [[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38],
        [40, 42, 44, 46, 48],
        [50, 52, 54, 56, 58]]])

In [399]:
np.hstack((a,d))

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [30, 32, 34, 36, 38, 40, 42, 44, 46, 48],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]])

In [400]:
np.vstack((a,d))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

# 11.splittig
    split(array_name,no_of_splits)
    

In [403]:
a=np.arange(16)

In [404]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [408]:
np.split(a,4)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15])]

In [409]:
np.split(a,8)

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11]),
 array([12, 13]),
 array([14, 15])]

In [411]:
d=a.reshape(4,4)

In [412]:
np.vsplit(d,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [413]:
np.hsplit(d,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# 12.searching
    

In [417]:
np.where(d%5==0)

(array([0, 1, 2, 3], dtype=int64), array([0, 1, 2, 3], dtype=int64))

# 13.sort 

In [363]:
np.sort(v)

array([  2,   4,   5,   6,   7,  10, 500])

In [364]:
a

array([ 10,   2, 500,   4,   5,   6,   7])

In [365]:
np.sort(a)

array([  2,   4,   5,   6,   7,  10, 500])

In [366]:
np.sort(c)

array([1, 2, 3, 4, 5, 6, 7])

# Arithematic operations
  * shape must be equal(element to element operations will be done)
  * 2 nd array should have atleast one dim(elments ==no of rows in first array)
  * 2 nd array hving single elements then als owe can apply the opratons
  
  np.add(first_array,second_array)
  np.subtract(first_array,second_array)
  np.multiply(first_array,second_array)
  np.divide(first_array,second_array)
  np.power(first_array,second_array)
  np.mod(first_array,second_array)
  np.real(first_array,second_array)
  np.imag(first_array,second_array)
  np.conjugate(first_array,second_array)

In [429]:
a=np.arange(9)

In [430]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [437]:
a=a.reshape(3,3)

In [438]:
b=np.ones([3,3],dtype="int")

In [439]:
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [440]:
np.shape(a)

(3, 3)

In [441]:
np.shape(b)

(3, 3)

In [442]:
c=np.array([10,20,30])

In [443]:
c

array([10, 20, 30])

In [444]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [445]:
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [446]:
c

array([10, 20, 30])

In [447]:
np.add(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [448]:
np.add(a,c)

array([[10, 21, 32],
       [13, 24, 35],
       [16, 27, 38]])

In [450]:
np.subtract(b,a)
np.subtract(a,b)

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [455]:
x=np.array([3+5j,10-4j])

In [458]:
x

array([ 3.+5.j, 10.-4.j])

In [459]:
np.real(x)

array([ 3., 10.])

In [460]:
np.imag(x)

array([ 5., -4.])

In [461]:
np.conjugate(x)

array([ 3.-5.j, 10.+4.j])

# Statistical Functions
    amin()
    amax()
    avarage()
    mean()
    median()
    var()
    std()
    

In [463]:
a=np.array([[56,23,48],[45,89,63,],[12,58,97]])

In [464]:
a

array([[56, 23, 48],
       [45, 89, 63],
       [12, 58, 97]])

In [469]:
np.amin(a)
np.amin(a,axis=0)
np.amin(a,axis=1)

array([23, 45, 12])

In [470]:
np.amax(a)
np.amax(a,axis=0)
np.amax(a,axis=1)

array([56, 89, 97])

In [476]:
np.average(a)
np.average(a,axis=0)
np.average(a,axis=1)

array([42.33333333, 65.66666667, 55.66666667])

In [477]:
np.mean(a)


54.55555555555556

In [478]:
np.mean(a,axis=0)


array([37.66666667, 56.66666667, 69.33333333])

In [479]:
np.mean(a,axis=1)

array([42.33333333, 65.66666667, 55.66666667])

In [480]:
np.median(a)

56.0

In [481]:
np.median(a,axis=0)

array([45., 58., 63.])

In [482]:
np.median(a,axis=1)

array([48., 63., 58.])